common: &common
  adapter: postgresql
  username: postgres
  password: postgres 
  
development:
  <<: *common
  database: myapp_development

test:
  <<: *common
  database: myapp_test

production:
  <<: *common
  database: myapp_production




